var enrolAppointmentTpl = new Ext.XTemplate([
	     '<tpl><h5 style="padding-left:10px">ENROLLMENT DETAILS</h5></tpl>',
         '<tpl for=".">',				 
			 '<tpl if="career">',
			 	'<div class="cname">', 
                      '<div>{descr254}</div>',
					  '<div style="padding-left:20px;font-weight:">Emplid: {emplid}</div>',
					  '<div style="padding-left:20px;font-weight:normal">Career:  {career}</div>',
					  '<div style="padding-left:20px;font-weight:normal">Institution:  {institute}</div>',
					  '<div style="padding-left:20px;font-weight:normal">Term:  {term} </div>',
					  '<div style="padding-left:20px;font-weight:normal">Prim prog:  {acad_prog}</div>',
				'</div>',	
				'<div class="subheader"></div>',
				'<div class="cname">',
       			'<div class="datetime">',
           			'<div>{sdate} To {endDate} <br> <big>{mstarttime} - {mendtime}</big></div>',
   				'</div>',
   				'<div><span class="descr">Session: {session}</span><br> <span class="descr">Appointment.No:{appointment_no}</span></div>',
   				'</div>',  				
   			
   				'<div class="subheader">',    				
				
						'<div class="cell4">', 
						  '<div class="cell3">',  
						    '<div class="cell2">',  
						      '<div class="cell1">',  
						        '<div class="cell2a">',  
						          '<div class="cell3a">',  
						            '<div class="cell4a">',  
						              'For this appointment',							
						            '</div>', 
						            'For this session',
						          '</div>', 
						          'For The Term',
						        '</div>', 
								'units limits',							        
						      '</div>', 							
						    '</div>', 
						  '</div>', 
						'</div>',						
				'</div>',
		 '<tpl if="max_a">',
			 	'<div class="subheadernobg">',
			 		'<div class="cell4">', 
					  '<div class="cell3">',  
					    '<div class="cell2">',  
					      '<div class="cell1">',  
					        '<div class="cell2a">',  
					          '<div class="cell3a">',  
					            '<div class="cell4a">',  
					              '{max_a}',							
					            '</div>', 
					            '{max_s}',
					          '</div>', 
					          '{max_t}',
					        '</div>',
					        'Maximum', 							        
					      '</div>', 							
					    '</div>', 
					  '</div>', 
					'</div>',    
			   '</div>',
			 '</tpl>',
		'<tpl if="nogpa_a">',
			 	'<div class="subheadernobg">',
			 		'<div class="cell4">', 
					  '<div class="cell3">',  
					    '<div class="cell2">',  
					      '<div class="cell1">',  
					        '<div class="cell2a">',  
					          '<div class="cell3a">',  
					            '<div class="cell4a">',  
					              '{nogpa_a}',							
					            '</div>', 
					            '{nogpa_s}',
					          '</div>', 
					          '{nogpa_t}',
					        '</div>',
					        'No GPA Units', 							        
					      '</div>', 							
					    '</div>', 
					  '</div>', 
					'</div>',    
			   '</div>',				
			 '</tpl>',
		 '<tpl if="maxaud_a">',
			 	'<div class="subheadernobg">',
			 		'<div class="cell4">', 
					  '<div class="cell3">',  
					    '<div class="cell2">',  
					      '<div class="cell1">',  
					        '<div class="cell2a">',  
					          '<div class="cell3a">',  
					            '<div class="cell4a">',  
					              '{maxaud_a}',							
					            '</div>', 
					            '{maxaud_s}',
					          '</div>', 
					          '{maxaud_t}',
					        '</div>',
					        'Audit Units', 							        
					      '</div>', 							
					    '</div>', 
					  '</div>', 
					'</div>',    
			   '</div>',				  
			 '</tpl>',
		'<tpl if="maxWL_a">',
			 	'<div class="subheadernobg">',
			 		'<div class="cell4">', 
					  '<div class="cell3">',  
					    '<div class="cell2">',  
					      '<div class="cell1">',  
					        '<div class="cell2a">',  
					          '<div class="cell3a">',  
					            '<div class="cell4a">',  
					              '{maxWL_a}',							
					            '</div>', 
					            '{maxWL_s}',
					          '</div>', 
					          '{maxWL_t}',
					        '</div>',
					        'Waitlist Units', 							        
					      '</div>', 							
					    '</div>', 
					  '</div>', 
					'</div>',    
			   '</div>',				 
		 '</tpl>',			 
		'</tpl>',
    '</tpl>'
]);


       
goCampus.views.enrolAppointment = new Ext.Panel({
      id: 'enrolAppoint',           
      layout : 'fit',
      scroll : 'vertical',
	  styleHtmlContent: true,
      dockedItems: [{
			  	layout:'fit',
				id: 'enrol_appoint',
			  	xtype: 'toolbar',
			  	title: 'Enroll Appointment',
				cls:'small_title',
				ui:'light'
			  }] 
});


function callEnrollAppointmentWS(){
	loadingMask = new Ext.LoadMask(Ext.getBody(), {msg:"Loading..."});
	loadingMask.show();
	Ext.util.JSONP.request({
            //url: './JsonServlet',
            url: './jsons/enrolappointment.json',
           /* params: {
               format: 'json',
               callback: 'callback',
			   ws: 'SEA',
			   emplid: localStorage.getItem('userid'),
			   institute : 'PSUNV',
			   career : 'UGRD',
			   term: '0675'
           },*/
            method: 'GET', 
            callbackKey: 'callback',
            callback: function(result) {    
		  if(result){
			  goCampus.views.enrolAppointment.update(enrolAppointmentTpl.applyTemplate(result));
		  }else{
		  	alert("Error. Server not responding");
		  }                                                                
          loadingMask.hide();
          }
	});
}
